--exec dbms_stats.gather_table_stats('DWH_DDS','D_OC_CAMPAIGN',estimate_percent => 70,cascade => TRUE);


DROP TABLE ADHOC.RUN_OMNI_ACC_ADOPTION ;


CREATE TABLE ADHOC.RUN_OMNI_ACC_ADOPTION COMPRESS AS
SELECT 
CAMPAIGN_ID_AZ__C
,CAMPAIGN_ID_AZ__C ||'_P'|| STAGE_SEQUENCE_AZ__C DPHS_ID
,H1.CUS_SK CUS_ID
,H1.CUS_BK DUO_ID
,ACCOUNT_AZ__C
,ID
,TRUNC(coalesce(STAGE_ASSIGNED_DATE_AZ__C,CREATEDDATE))  START_DT
,TRUNC(coalesce(STAGE_COMPLETION_DATE_AZ__C,CAMPAIGN_END_DATE_AZ__C)) END_DT
,DURATION_IN_DAYS_AZ__C
,INITIAL_STAGE__C
,ACTIVE_AZ__C
,STAGE_SEQUENCE_AZ__C
,STATUS_AZ__C
,CAMPAIGN_END_DATE_AZ__C
,     D_OC_CAMP.DCMP_LINEAR_FLG
, NVL(D_OC_CAMP.DCMP_DDIV_ID ,'NV')S_DCMP_DDIV_ID
, NVL(D_OC_CAMP.DCMP_BRAND,-1) S_DCMP_PRD_ID
--, CAMPAIGN_NAME_AZ__C, CAMPAIGN_START_DATE_AZ__C, CAMPAIGN_END_DATE_AZ__C
--, BRAND_AZ__C, NAME, PERSONA_AZ__C, ACCOUNT_AZ__C, t1.DWH_LOAD_TS,DWH_DELETE_FLG
--, CREATEDBYID, CREATEDDATE, LASTMODIFIEDBYID, LASTMODIFIEDDATE--,SYSTEMMODSTAMP
--,  SCORE_AZ__C, STAGE_ID_AZ__C
--, STAGE_NAME_AZ__C, STAGE_SEQUENCE_AZ__C 
, COUNT(*) OVER ( PARTITION BY CAMPAIGN_ID_AZ__C,ACCOUNT_AZ__C) CNT
FROM DWH_STAGE_GDH.OMNI_ACCOUNT_ADOPTION_AZ__C_VW t1
INNER JOIN DWH_DDS.D_OC_CAMPAIGN D_OC_CAMP on CAMPAIGN_ID_AZ__C = D_OC_CAMP.DCMP_ID  
LEFT OUTER JOIN DWH_DV.CUSTOMER_KEMA_VVAZ KEMA ON CUS_VVAZ_BK = ACCOUNT_AZ__C AND KEMA.DWH_STATUS = 'A'
LEFT OUTER JOIN DWH_DV.CUSTOMER_H H1 ON H1.CUS_SK = KEMA.CUS_SK  
WHERE (ID, t1.DWH_RUN_ID )   IN ( SELECT ID, MAX(DWH_RUN_ID) FROM DWH_STAGE_GDH.OMNI_ACCOUNT_ADOPTION_AZ__C_VW GROUP BY ID)
--AND ACTIVE_AZ__C = 'Y' 
AND NVL(STAGE_SEQUENCE_AZ__C,0)>0
AND DCMP_LINEAR_FLG = 0
--AND CAMPAIGN_ID_AZ__C = 'Tagrisso 2022 FLAURA'
AND DWH_DELETE_FLG = 'N'
--AND CAMPAIGN_ID_AZ__C = 'FRX-DE-THDO-Y21-R1'
--AND  TRUNC(CREATEDDATE) NOT IN (DATE '2021-10-05' )
--AND ACCOUNT_AZ__C = '001d000001Y8V8fAAF'
--AND H1.CUS_BK = 'DE741445'
ORDER BY CAMPAIGN_ID_AZ__C, ACCOUNT_AZ__C,STAGE_SEQUENCE_AZ__C
;

--- insert gereated rows 
DROP TABLE ADHOC.RUN_OMNI_ACC_ADOPTION_MONTH 
;

CREATE TABLE ADHOC.RUN_OMNI_ACC_ADOPTION_MONTH COMPRESS  AS
SELECT DATE_MONTH,
CUS_ID, DUO_ID, ACCOUNT_AZ__C,
CAMPAIGN_ID_AZ__C
,S_DCMP_DDIV_ID   
,S_DCMP_PRD_ID
, DPHS_ID
, DECODE(ACTIVE_AZ__C,'Y',1,'N',0) S_CURRENT_STAGE_FLG
, START_DT, END_DT
, DECODE(STATUS_AZ__C,'COMPLETED',1,0) OC_BADGE_FLG
, DCMP_LINEAR_FLG
, MAX(CASE WHEN TRUNC(DATE_MONTH,'MM') = TRUNC(SYSDATE-2,'MM') THEN 1 ELSE 0 END ) OVER ( PARTITION BY CAMPAIGN_ID_AZ__C,CUS_ID) OC_TG_FLG
--, 1 CNT
 FROM (
    SELECT CAMPAIGN_ID_AZ__C, DPHS_ID, CUS_ID, DUO_ID, ACCOUNT_AZ__C, ID, START_DT, END_DT, DURATION_IN_DAYS_AZ__C, INITIAL_STAGE__C, ACTIVE_AZ__C, STAGE_SEQUENCE_AZ__C, STATUS_AZ__C, CAMPAIGN_END_DATE_AZ__C
    ,S_DCMP_DDIV_ID,S_DCMP_PRD_ID,DCMP_LINEAR_FLG, CNT FROM ADHOC.RUN_OMNI_ACC_ADOPTION t1
        UNION ALL 
    SELECT CAMPAIGN_ID_AZ__C, t2.DPHS_ID, CUS_ID, DUO_ID, ACCOUNT_AZ__C, ID||'_'||DPHS_SEQUENCE ID, START_DT, t1.CAMPAIGN_END_DATE_AZ__C END_DT, DURATION_IN_DAYS_AZ__C, 'N' INITIAL_STAGE__C, 'N' ACTIVE_AZ__C, DPHS_SEQUENCE STAGE_SEQUENCE_AZ__C, 'CURRENT' STATUS_AZ__C, CAMPAIGN_END_DATE_AZ__C
    ,S_DCMP_DDIV_ID,S_DCMP_PRD_ID,DCMP_LINEAR_FLG, 0 CNT
    FROM ADHOC.RUN_OMNI_ACC_ADOPTION t1 
    INNER JOIN DWH_DDS.D_OC_PHASE t2 on 1=1 AND DPHS_OCMP_ID = CAMPAIGN_ID_AZ__C
    WHERE STAGE_SEQUENCE_AZ__C = 1
    AND  ( t2.DPHS_ID,CUS_ID ) NOT IN (SELECT DPHS_ID,CUS_ID FROM ADHOC.RUN_OMNI_ACC_ADOPTION)
)   INNER JOIN (SELECT ADD_MONTHS(DATE '2021-10-01',(rownum-1)) DATE_MONTH,LAST_DAY(ADD_MONTHS(DATE '2021-10-01',(rownum-1))) DATUM_LAST  FROM ALL_OBJECTS WHERE ROWNUM < 50) ON DATE_MONTH < SYSDATE+30 AND  DATUM_LAST BETWEEN START_DT AND CAMPAIGN_END_DATE_AZ__C
ORDER BY CAMPAIGN_ID_AZ__C, ACCOUNT_AZ__C,DATE_MONTH,STAGE_SEQUENCE_AZ__C
;



--############################################################################

TRUNCATE TABLE DWH_DDS.D_OC_CAMPAIGN
;

INSERT INTO DWH_DDS.D_OC_CAMPAIGN
SELECT  CAMPAIGN_ID_AZ__C DCMP_ID, MAX(CAMPAIGN_NAME_AZ__C) DCMP_NAME, 
(SELECT PRD_SK FROM DWH_DV.PRODUCT_KEMA_VVAZ WHERE PRD_VVAZ_BK = BRAND_AZ__C)  DCMP_BRAND
,DECODE(CAMPAIGN_ID_AZ__C,'AZ Trixeo 2021','xxxxAZ_RESPI_INH','TRX-DE-THDO-Y21','AZ_RESPI_INH','AZ SAPHNELO 2022','IMMUNO_SLE','Fasenra Omnichannel 2022','AZ_RESPI_BX'
,'FORXIGA CKD SANTIS 2022','SAN_MIX'
,'TRIXEO SANTIS LITE', 'SAN_MIX'
,'FpcMD','CVRM_CKD'
--,'FRX-DE-THDO-Y21-R1','CVRM_CKD' alt kampagne
,'Tagrisso 2022 FLAURA','ONKO_LUNG_TKI'
,'deJ3W','CVRM_HF' -- Forxiga CVRM_2022_03_FOR_HF_AZ_lite_OmniCC Germany Y2022
,'eF9GL','CVRM_DIABETO' -- Forxiga CVRM_2022_04_FOR_DIAB_AZ_lite_OmniCC Germany Y2022
,'kVVoj','ONKO_PAC'
,'9UN5v','AZ_RESPI_BX_TEZ'   -- Tezspire R&I 2002_TEZ_Generic Germany Y2022
,'TbD_'||CAMPAIGN_ID_AZ__C) 
    DCMP_DDIV_ID
,  CASE WHEN CAMPAIGN_ID_AZ__C IN ('Tagrisso Seltene Mutationen','Tagrisso Sequenz','Tagrisso 2022 FLAURA') THEN 0 ELSE 1 END DCMP_LINEAR_FLG
--, BRAND_INDICATION_AZ__C,
, MAX(CAMPAIGN_START_DATE_AZ__C)DCMP_START_DT
, NVL(MAX(CAMPAIGN_END_DATE_AZ__C),DATE '2099-12-31') DCMP_END_DT 
--, COUNTRY_CODE_AZ__C, MAX(PERSONA_AZ__C)PERSONA_AZ__C, COUNT(*)
, sysdate, 4711
FROM DWH_STAGE_GDH.OMNI_ACCOUNT_ADOPTION_AZ__C_VW t1 
WHERE (ID, t1.DWH_RUN_ID )   IN ( SELECT ID, MAX(DWH_RUN_ID) FROM DWH_STAGE_GDH.OMNI_ACCOUNT_ADOPTION_AZ__C_VW GROUP BY ID)
AND NVL(STAGE_SEQUENCE_AZ__C,0)>0
GROUP BY BRAND_AZ__C,   CAMPAIGN_ID_AZ__C --, CAMPAIGN_NAME_AZ__C --,  BRAND_INDICATION_AZ__C,COUNTRY_CODE_AZ__C
ORDER BY  CAMPAIGN_ID_AZ__C
;


TRUNCATE TABLE DWH_DDS.D_OC_PHASE
;

INSERT INTO DWH_DDS.D_OC_PHASE
SELECT CAMPAIGN_ID_AZ__C ||'_P'|| STAGE_SEQUENCE_AZ__C DPHS_ID
--, MIN(STAGE_NAME_AZ__C) KEEP (DENSE_RANK LAST ORDER BY CREATEDDATE ) DPHS_NAME
, MIN(STAGE_LABEL_AZ__C)    KEEP (DENSE_RANK LAST ORDER BY CREATEDDATE ) DPHS_NAME
, MIN(STAGE_SEQUENCE_AZ__C) KEEP (DENSE_RANK LAST ORDER BY CREATEDDATE ) DPHS_SEQUENCE
, 0 DPHS_RATIO
,CAMPAIGN_ID_AZ__C  DPHS_OCMP_ID
, sysdate, 4711
FROM DWH_STAGE_GDH.OMNI_STAGE_AZ__C_VW t1
WHERE 1=1
AND (ID, t1.DWH_RUN_ID )  IN ( SELECT ID, MAX(DWH_RUN_ID) FROM DWH_STAGE_GDH.OMNI_STAGE_AZ__C_VW GROUP BY ID)
--AND NVL(SHARING_GROUP_AZ__C||CAMPAIGN_ID_AZ__C,'NV') NOT IN (  'DE_SAN_MIXTRX-DE-THDO-Y21','DE_CVRM_CVTRX-DE-THDO-Y21')
--AND CAMPAIGN_ID_AZ__C IN ( 'FRX-DE-THDO-Y21-R1','TRX-DE-THDO-Y21')
AND ISDELETED = 'N'
AND NVL(STAGE_SEQUENCE_AZ__C,0)>0
GROUP BY CAMPAIGN_ID_AZ__C,STAGE_SEQUENCE_AZ__C
ORDER BY CAMPAIGN_ID_AZ__C,STAGE_SEQUENCE_AZ__C
;

COMMIT;

DROP TABLE ADHOC.RUN_TIME_MONTH;

CREATE TABLE ADHOC.RUN_TIME_MONTH AS
SELECT * FROM (
SELECT ADD_MONTHS(DATE '2021-10-01',(rownum-1)) DATUM,LAST_DAY(ADD_MONTHS(DATE '2021-10-01',(rownum-1))) DATUM_LAST  FROM ALL_OBJECTS WHERE ROWNUM < 19
) WHERE DATUM < sysdate +33
;
 
/*
CREATE TABLE DWH_DDS.F_OC_CAMPAIGN_CUS 
( FTCF_DADL_ID, FTCF_DCUS_ID, FTCF_DTIME_ID, FTCF_MONTH_DATE
, FTCF_DCELL_ID, FTCF_DCTG_ID, FTCF_DCTG_ATTR_01, FTCF_DCTG_ATTR_02
, FTCF_VIS_CURRENT_TCF, FTCF_DIF_PHASING, FTCF_VIS_AVERAGE_TCF_MONTHLY, FTCF_VIS_AVERAGE_TCF_YTD, FTCF_VIS_AVERAGE_TCF, FTCF_VIS, FTCF_VIS_IDET, FTCF_VIS_IDET_FACT, FTCF_VIS_YTD, FTCF_VIS_OOT_YTD
, FTCF_VIS_COV_L3M, FTCF_VIS_COV_YTD, FTCF_VIS_TCI, FTCF_VIS_LAST_DATE, FTCF_NON_VIS_YTD, FTCF_VIS_NEXT_DATE--, FTCF_VIS_NEXT_WEEK
, FTCF_STATUS  
, CONSTRAINT PK_F_TCF_CUS PRIMARY KEY (FTCF_DADL_ID, FTCF_DCELL_ID,FTCF_DCTG_ID,FTCF_DCUS_ID,FTCF_DTIME_ID) -- wegen Performance
)
PARTITION BY LIST (FTCF_STATUS)
      (
      PARTITION F_TCF_CUS_ACTIVE   VALUES ('Active'),
      PARTITION F_TCF_CUS_INACTIVE VALUES ('Inactive')
      )
*/




DROP TABLE DWH_DDS.F_OC_CAMPAIGN_CUS PURGE;

CREATE TABLE DWH_DDS.F_OC_CAMPAIGN_CUS
COMPRESS AS
SELECT DCMP_ID FOCC_DCMP_ID
,DCUS_ID FOCC_DCUS_ID
, MAX(DCUS_CELL_ID_1) FOCC_DCELL_ID
--,MAX(S_DPHS_ID) FOCC_DPHS_ID -- aus GDH fehlt aktuell erste Phase 0????  Seit wann in der Phase, dann wieder ak
,S_DPHS_ID  FOCC_DPHS_ID
,MAX(OC_TG_FLG) FOCC_TG_FLG 
,MAX(OC_BADGE_FLG) FOCC_BADGE_FLG
,LAST_VALUE (MAX(S_DPHS_ID)) OVER (PARTITION BY DCMP_ID,DCUS_ID ORDER BY DATUM  RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING)  FOCC_CUS_CUR_DPHS_ID -- aus GDH fehlt aktuell erste Phase 0????  Seit wann in der Phase, dann wieder ak
, DATUM FOCC_VALID_FROM  
, TO_CHAR(DATUM,'YYYYMMDD') FOCC_DTI_ID  
, GREATEST(DATUM-MAX(S_DCMP_START_DT),0) FOCC_PHASE_SINCE -- hier für die VISUALT relevant, 
, MAX(DCMP_BRAND) FOCC_DPRD_ID 
, MIN((SELECT MIN(SEGM) FROM ADHOC.RUN_ACT_SEGM_LKP WHERE XCUCC_CUS_ID = DCUS_ID AND PRD_SK = DCMP_BRAND AND TRUNC(SYSDATE) BETWEEN XCUCC_VALID_FROM AND XCUCC_VALID_TO)) FOCC_DPRD_SEGM 
--, MAX(DCUS_CUR_SEGM_15) FOCC_DPRD_SEGM     --Segmentierung CKD
--- Metriken???
, 1 FOCC_CUS_CNT
, DECODE(MAX(S_DPHS_ID),LEAD (MAX(S_DPHS_ID)) OVER( PARTITION BY DCUS_ID,DCUS_ID ORDER BY DATUM DESC),0,1) FOCC_PHASE_ADMISSION -- Zugänge
--, MAX(DCUS_CAT_8) FOCC_CONSENT_VAE --Relevant`? VAE Consent AZ was ist mit Santis?
--, MAX(DCUS_CAT_17) FOCC_CONSENT_MMC --Relevant`?  Consent San MMC Opt_Out_vod Opt_In_vod
, MAX(CASE WHEN DCUS_CAT_8  = 'Opt_In_vod'  AND TRUNC(DATUM,'MM')>= TO_DATE(DCUS_CAT_9 ,'DD.MM.YYYY') THEN 1 ELSE 0 END) FOCC_OPTIN_VAE 
, MAX(CASE WHEN DCUS_CAT_8  = 'Opt_Out_vod' AND TRUNC(DATUM,'MM')>= TO_DATE(DCUS_CAT_9 ,'DD.MM.YYYY') THEN 1 ELSE 0 END) FOCC_OPTOUT_VAE
, MAX(CASE WHEN DCUS_CAT_17 = 'Opt_In_vod'  AND TRUNC(DATUM,'MM')>= TO_DATE(DCUS_CAT_18,'DD.MM.YYYY') THEN 1 ELSE 0 END) FOCC_OPTIN_MMC
, MAX(CASE WHEN DCUS_CAT_17 = 'Opt_Out_vod' AND TRUNC(DATUM,'MM')>= TO_DATE(DCUS_CAT_18,'DD.MM.YYYY') THEN 1 ELSE 0 END) FOCC_OPTOUT_MMC
, MAX(DECODE(FDESA_DATE,NULL,0,1)) FOCC_COVERAGE_YTD
, CASE WHEN DATUM - MAX(FDESA_DATE) < 15 THEN 1 ELSE 0 END  FOCC_COVERAGE_L3W --Weeeks=
, MAX(FDESA_DATE) FOCC_LAST_ACT_DT
--, MAX(CASE WHEN FDESA_DACTT_ID IN ( 'VAE-Activity_|_VAE_sent_|_vae_sent') AND CAMPAIGN_ID IS NOT NULL THEN 1 ELSE 0 END) FOCC_CUS_ACTIVATED -- Hier muss der Conent identifiziert werden.. aktuell NUR VAE
--, MAX(CASE WHEN FDESA_DACTT_ID IN ( 'VAE-Activity_|_VAE_sent_|_vae_sent') THEN 1 ELSE 0 END) FOCC_CUS_ACTIVATED_TEST -- Hier muss der Conent identifiziert werden.. aktuell NUR VAE
, MAX(DECODE(FDESA_DATE,NULL,0,1)) FOCC_CUS_ACTIVATED -- reached
, MAX(CASE WHEN TRUNC(FDESA_DATE,'MM')= TRUNC(DATUM,'MM') AND NVL(CAMPAIGN_ELEMENT,'NV') NOT IN ('NV', 'Letter, Fax, Service') THEN 1 ELSE 0 END)  FOCC_COV_REACHED
, MAX(CASE WHEN TRUNC(FDESA_DATE,'MM')= TRUNC(DATUM,'MM') AND CAMPAIGN_ELEMENT = 'Field Force'          THEN 1 ELSE 0 END)  FOCC_COV_F2F
, MAX(CASE WHEN TRUNC(FDESA_DATE,'MM')= TRUNC(DATUM,'MM') AND CAMPAIGN_ELEMENT = 'Email'                THEN 1 ELSE 0 END)  FOCC_COV_EMAIL
, MAX(CASE WHEN TRUNC(FDESA_DATE,'MM')= TRUNC(DATUM,'MM') AND CAMPAIGN_ELEMENT = 'MMC'                  THEN 1 ELSE 0 END)  FOCC_COV_MMC
, MAX(CASE WHEN TRUNC(FDESA_DATE,'MM')= TRUNC(DATUM,'MM') AND CAMPAIGN_ELEMENT = 'Event'                THEN 1 ELSE 0 END)  FOCC_COV_EVENT
, MAX(CASE WHEN TRUNC(FDESA_DATE,'MM')= TRUNC(DATUM,'MM') AND CAMPAIGN_ELEMENT = 'Letter, Fax, Service' THEN 1 ELSE 0 END)  FOCC_COV_SERV
, MAX(CASE WHEN FDESA_DACTT_ID IN ( 'VAE-Activity_|_VAE_opened_|_vae_opened', 'Webcontent_|_MeinMedCampus_|_Medical-Content','Webcontent_|_NonOCSMeinMedCampus_|_Medical-Content') THEN 1 ELSE 0 END)  FOCC_CUS_ENGAGED -- Kunden hat selbst Interagiert.
, SUM(CASE WHEN TRUNC(FDESA_DATE,'MM')= TRUNC(DATUM,'MM') AND FDESA_DACTT_ID IN ( 'VAE-Activity_|_VAE_sent_|_vae_sent') THEN 1 ELSE 0 END) FOCC_VAE_SENT  
, SUM(CASE WHEN TRUNC(FDESA_DATE,'MM')= TRUNC(DATUM,'MM') AND FDESA_DACTT_ID IN ( 'VAE-Activity_|_VAE_opened_|_vae_opened') THEN 1 ELSE 0 END) FOCC_VAE_OPEN  
, SUM(CASE WHEN TRUNC(FDESA_DATE,'MM')= TRUNC(DATUM,'MM') AND FDESA_DACTT_ID IN ( 'VAE-Activity_|_VAE_clicked_|_vae_clicked') THEN 1 ELSE 0 END) FOCC_VAE_CLICK  
, SUM(CASE WHEN TRUNC(FDESA_DATE,'MM')= TRUNC(DATUM,'MM') AND FDESA_DACTT_ID IN ( 'Webcontent_|_MeinMedCampus_|_Medical-Content','Webcontent_|_NonOCSMeinMedCampus_|_Medical-Content') THEN 1 ELSE 0 END) FOCC_MMC_ACT --MMC ALL Aktivitäten und MMC_visits
, SUM(CASE WHEN TRUNC(FDESA_DATE,'MM')= TRUNC(DATUM,'MM') AND FDESA_DACTT_ID IN ( 'Webcontent_|_MeinMedCampus_|_Medical-Content') THEN 1 ELSE 0 END) FOCC_MMC_VIDEO -- MMC_Video_Download -- aktuell Dummy
-- Muster?
, SUM(CASE WHEN TRUNC(FDESA_DATE,'MM')= TRUNC(DATUM,'MM') AND FDESA_DDET_ID IN ( 'D','NV') AND FDESA_ACTT_DESC_SC = 'visual' THEN 1 ELSE 0 END) FOCC_CON_VISUAL
, SUM(CASE WHEN TRUNC(FDESA_DATE,'MM')= TRUNC(DATUM,'MM') AND FDESA_DDET_ID IN ( 'D','NV') AND FDESA_ACTT_DESC_SC = 'virtual' THEN 1 ELSE 0 END) FOCC_CON_VIRTUAL
, SUM(CASE WHEN TRUNC(FDESA_DATE,'MM')= TRUNC(DATUM,'MM') AND FDESA_DDET_ID IN ( 'D','NV') AND FDESA_ACTT_DESC_SC = 'non-visual' THEN 1 ELSE 0 END) FOCC_NON_VISUAL
, sysdate DWH_UPDATE_DATE
, 4711 DWH_RUN_ID 
FROM (
    SELECT 
     dcus.*
    ,oc1.*
    ,occ.*
    ,RTIMEMONTH.*
    ,FDESA.*
    ,t3.*
        , CASE 
            WHEN FDESA_ACTT_DESC_SC IN ('Event','MMC') THEN FDESA_ACTT_DESC_SC
            WHEN UPPER(FDESA_ACTT_DESC_KK) LIKE '%FOBI%' THEN 'Event'
            WHEN FDESA_ACTT_DESC_SC IN ('virtual','visual') THEN 'Field Force'
            WHEN UPPER(FDESA_ACTT_DESC_KK) LIKE '%EMAIL%' OR FDESA_ACTT_DESC_KK IN ('VAE Clickrate','VAE Sentrate deaktiviert') THEN 'Email'
            WHEN FDESA_ACTT_DESC_KK LIKE '%Service' OR FDESA_ACTT_DESC_KK LIKE '%Fax' OR FDESA_ACTT_DESC_KK LIKE '%Brief'  THEN 'Letter, Fax, Service'
        ELSE 'NV' END CAMPAIGN_ELEMENT
    FROM DWH_DDS.D_CUSTOMER dcus
    INNER JOIN (
        SELECT * FROM ADHOC.RUN_OMNI_CAMPAIGN_CUS 
        WHERE DCMP_LINEAR_FLG = 1
            UNION ALL
        SELECT * FROM ADHOC.RUN_OMNI_ACC_ADOPTION_MONTH 
        WHERE DCMP_LINEAR_FLG = 0
    ) oc1 ON oc1.CUS_SK = DCUS_ID
    INNER JOIN DWH_DDS.D_OC_CAMPAIGN occ ON DCMP_ID = oc1.S_DCMP_ID
    INNER JOIN  ADHOC.RUN_TIME_MONTH RTIMEMONTH ON oc1.DATE_MONTH = DATUM 
    LEFT OUTER JOIN DWH_DDS.F_DETAIL_SAMPLE FDESA 
            ON  FDESA.FDESA_DCUS_ID = DCUS_ID AND FDESA_DATE BETWEEN DCMP_START_DT-14 AND DATUM_LAST --AND NVL(CAMPAIGN_ID,'NV') IN ( 'NV',  DCMP_ID)
            AND FDESA.FDESA_DCMP_ID = oc1.S_DCMP_ID -- neues Mapping der Aktivitäten 
           -- AND NVL(FDESA_DDIV_ID,'NV') = NVL(S_DCMP_DDIV_ID,'NV1') -- IN ( 'NV','CVRM_CKD') MMC und Events fallen hier vermutlich raus.
            --AND ( DCMP_BRAND = FDESA_DPRD_ID OR FDESA_ACTT_DESC_SC IN ( 'Event','MMC')) -- Test Event und MMC??? geht aktuell nicht, da kein Produkt  
                --AND FDESA_DAST_ID = 'Submitted' AND FDESA_DDESE_ID IN ( 0,1) AND FDESA_DDET_ID IN ( 'D','NV') 
                --AND FDESA_DATE > DATE '2021-09-01'
    LEFT OUTER JOIN DWH_STAGE_MISC.OC_OM_MAPPER t3 ON  FDESA_CALL_OUTCOME = CONTENT_CDH_ID
)
GROUP BY DCMP_ID,DCUS_ID,DATUM,S_DPHS_ID
ORDER BY DCMP_ID,DCUS_ID,DATUM,S_DPHS_ID
;

-- NV Sätze für die Phasen /*+ use_hash(dcus,oc1) */  * /*+ USE_HASH(t1,t3,RTIMEMONTH,t3,oc1) */

INSERT INTO DWH_DDS.F_OC_CAMPAIGN_CUS
(FOCC_DCMP_ID,  FOCC_DCUS_ID, FOCC_DPHS_ID, FOCC_CUS_CUR_DPHS_ID, FOCC_VALID_FROM, FOCC_DTI_ID, FOCC_DPRD_ID, DWH_UPDATE_DATE, DWH_RUN_ID)
SELECT DISTINCT FOCC_DCMP_ID, -1 FOCC_DCUS_ID, DPHS_ID FOCC_DPHS_ID,  DPHS_ID FOCC_CUS_CUR_DPHS_ID, FOCC_VALID_FROM, FOCC_DTI_ID, FOCC_DPRD_ID, t1.DWH_UPDATE_DATE, t1.DWH_RUN_ID FROM  DWH_DDS.F_OC_CAMPAIGN_CUS t1
INNER JOIN DWH_DDS.D_OC_PHASE ON FOCC_DCMP_ID = DPHS_OCMP_ID
ORDER BY 4,5
;


GRANT SELECT ON DWH_DDS.F_OC_CAMPAIGN_CUS TO DWH_DDS WITH GRANT OPTION;

GRANT SELECT ON DWH_DDS.F_OC_CAMPAIGN_CUS TO ADHOC_REPORTS WITH GRANT OPTION;

GRANT SELECT ON DWH_DDS.F_OC_CAMPAIGN_CUS TO DWH_APP_PWA WITH GRANT OPTION;

GRANT SELECT ON DWH_DDS.F_OC_CAMPAIGN_CUS TO DWH_RO;

GRANT SELECT ON DWH_DDS.F_OC_CAMPAIGN_CUS TO MSTR_SYS_DE;



